import { Inter } from 'next/font/google';
import '../../public/css/common.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });
console.log('here');
export const metadata = {
    title: "kjiyu's next Blog",
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
    // const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}topics`, {
    //     next: { revalidate: 0 },
    // });
    // const topics = await res.json();

    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="main-wrap">{children}</div>
            </body>
        </html>
    );
}
