// 모달
export const TYPE = {
    // 모달
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    OPEN_CONFIRM_MODAL: 'OPEN_CONFIRM_MODAL',
    CLOSE_CONFIRM_MODAL: 'CLOSE_CONFIRM_MODAL',
    // 로그인
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    // 로그아웃
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    // 회원가입
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
    // 에러 클리어
    CLEAR_ERROR_REQUEST: 'CLEAR_ERROR_REQUEST',
    CLEAR_ERROR_SUCCESS: 'CLEAR_ERROR_SUCCESS',
    CLEAR_ERROR_FAILURE: 'CLEAR_ERROR_FAILURE',
    // 에러 클리어
    LOADING_REQUEST: 'LOADING_REQUEST',
    LOADING_SUCCESS: 'LOADING_SUCCESS',
    LOADING_FAILURE: 'LOADING_FAILURE',
};
